#!/bin/sh

set -e

# Function adaption of aesd-char-driver/aesdchar_load script
aesdchar_load() {
	module="aesdchar"
	device="aesdchar"
	mode="664"

	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	modprobe $module || exit 1

	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
	if [ ! -z ${major} ]; then
		rm -f /dev/${device}
		mknod /dev/${device} c $major 0
		chgrp $group /dev/${device}
		chmod $mode /dev/${device}
	fi
}

# Function adaption of aesd-char-driver/aesdchar_unload script
aesdchar_unload() {
	module="aesdchar"
	device="aesdchar"

	rmmod $module || exit 1

	rm -f /dev/${device}
}

case "$1" in
	start)
		aesdchar_load
		;;
	stop)
		aesdchar_unload
		;;
	*)
		echo "Usage $0 {start|stop}"
		exit 1
esac

exit 0
